### ISSUE TITLE
Mention that H610S and H615C have left and right rails

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#102]
Page: [Install H-series hardware](https://docs.netapp.com/us-en/hci/docs/task_hci_installhw.html)

The rails for the H615C and H610S are not universal, there is a left and right rail.  The screw hole needs to be positioned towards the bottom so that the H610S/H615C thumb-screw can secure the chassis to the rail.

Can you add this to avoid the ocassional upside-down mounting of those rails?

**Comment by amgrissino** [comment]
Got it, @scaleoutsean. Thank you! We'll get this info in to avoid any upside-down mounting!

**Comment by amgrissino** [comment]
All set @scaleoutsean. Just fixed and pushed this out. If you don't see the change, please refresh your browser. Thanks again!
