### ISSUE TITLE
Should H-Series switches be documented in H/W installation section?

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#103]
In places where SN switch configuration is documented, we do not document putting the power cables in the rail before mounting and sometimes people end up with the power cable(s) taking up 1U of rack space.

![image](https://user-images.githubusercontent.com/16622642/93547458-ac0afa80-f997-11ea-87c4-afd2f0a5fea1.png)

Page: [NetApp HCI installation and deployment overview](https://docs.netapp.com/us-en/hci/docs/task_hci_getstarted.html)

**Comment by amgrissino** [comment]
Thanks, @scaleoutsean, for your thoughtful comments as usual. We'll get this updated - a quick check with Eng first to see if there are any other considerations.

**Comment by amgrissino** [comment]
Just an update, @scaleoutsean. We are working with Eng, as you know, to discuss other configurations.

**Comment by amgrissino** [comment]
Hi, @scaleoutsean - As you know, we've been working with the stakeholders and have planned to add links in this topic, https://docs.netapp.com/us-en/hci/docs/task_hci_installhw.html to the Mellanox Cabling Guide (https://fieldportal.netapp.com/content/1075535?assetComponentId=1077676) and the HW installation guide on the Mellanox site (https://docs.mellanox.com/pages/viewpage.action?pageId=6884619). In the HW install poster, we will include the same URLs.  Thanks for watching as always!

**Comment by netapp-amitha** [comment]
Hi @scaleoutsean, the changes we discussed via email have been published. I'm closing this issue. On a side node, we are creating steps for Mellanox switch replacement, which will be available soon.
Thank you for your feedback!
