### ISSUE TITLE
Make it easier to find Config Advisor

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#106]
Current

> In a web browser, download the Active IQ Config Advisor tool from the NetApp Support Site.

Suggested

In a web browser, navigate to the Tools section of the NetApp Support Site, search for Active IQ Config Advisor and download the tool.

Page: [Validate your environment with Active IQ Config Advisor](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_task_validate_config_advisor.html)

**Comment by amgrissino** [comment]
Thanks, @scaleoutsean. Good to be more specific. At the end of last week, we were in the middle of two updates and wanted to wait until those went out and cleared. Thanks, again!

**Comment by scaleoutsean** [comment]
Thank you! It seems some folks tend to look under Products rather than Tools, hence the suggestion.

**Comment by amgrissino** [comment]
All set, @scaleoutsean. Fixed. Will close this. Make sure to refresh your browser on that article.
