### ISSUE TITLE
ESX CLI command to recover failed network port on compute node 

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#108]
```
Run the following command to recover the ports: 
  sxcli network nic set -n vmnic2 -a
```
Did you mean `esxcli ...`?

Page: [Compute Firmware Bundle 2.27 Release Notes](https://docs.netapp.com/us-en/hci/docs/rn_compute_firmware_2.27.html)

**Comment by netapp-mwallis** [comment]
Hi Sean - many thanks for catching this.  This is now fixed and will roll out with the upcoming stack release.  Thanks again!  --Michael
