### ISSUE TITLE
Translate the BMC features into english

### ISSUE THREAD

**Issue by steadmandean** [NetAppDocs/hci#115]
Page: [Storage Firmware Bundle 2.27 Release Notes](https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.27.html)

Please rewrite the BMC features into sentences that help customers and our field teams in knowing what's being improved. Example, "(H610S) Added the H5Viewer RKVM feature" is not very descriptive. Recommendation: "Added H610S support for HTML5 browser BMC management."

**Comment by netapp-mwallis** [comment]
Thanks Dean - we'll fix this for the upcoming October content refresh for GitHub.

**Comment by netapp-mwallis** [comment]
Modified the descriptions:

* (H610S) Enabled INITRD support
* (H610S) Updated SSL help message about X.509 certificates
* (H610S) Disabled TLS 1.0 and 1.1 support to resolve security vulnerabilities
* (H610S, H410S) Added the ability to mount remote media using Redfish APIs
* (H610S) Added support for HTML5 web browser BMC management
* (H610S) Added remote syslog support, to help with remote data center monitoring and management

**Comment by netapp-mwallis** [comment]
Hi Dean - let me know if these descriptions are sufficient.  Thanks! @steadmandean
