### ISSUE TITLE
Clarify steps to whitelist Bintray FQDNs/URLs

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#116]
> 1. Use the Wget or cURL utilities to access a URL (repo.netapp.com, for example).
> 2. Receive a failure to access the URL (different from repo.netapp.com).

Not much happens after step one - repo.netapp.com redirects to bintray.com. Neither of the subdomains (`netapp-downloads.bintray.com`, `library.netapp.com`) end up being involved in this process. 

`repo.netapp.com` is an alias for `dl.bintray.com` but `wget` won't tell you about that unless you check with DNS client, while the `library.netapp.com` won't get used until you log in and actually download something (which wget repo.netapp.com doesn't do).

There ought to be a better method to determine what FQDNs and URLs should be allowed. Maybe better to watch logs from "download container" in HCC and use that than a simplistic `wget` command? Or does bintray have a public KB for that?

> All ports are TCP unless stated otherwise, and should be open bidirectionally.

Really???

Page: [Required network ports](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

**Comment by netapp-mwallis** [comment]
Hi Sean, thanks for your feedback.  We're looking in to your suggestion with the help of engineering.  Also, did you have a specific concern regarding the "All ports are TCP unless..."?

Thanks,
Michael

**Comment by scaleoutsean** [comment]
Hello @netapp-mwallis , thanks for the quick response. 

It's the latter part of that sentence that I suspect is wrong. 

It is very rarely that ports must be open bidirectionally. I don't know which really need to be - I can't think of any except iSCSI between two SF clusters that replicate to each other (those might use TCP/3260 and also serve iSCSI at the same port). For example Syslog redirection can go only Out (from SF) as SF doesn't offer log server features. Also these downloads for HCC - I'd be shocked if we had to open Incoming TCP/443 (or, if we had to open TCP/22 for Reverse SSH Tunnel - that's why it's call reverse because there's no need to have TCP/22 open for it).

**Comment by netapp-mwallis** [comment]
Thanks Sean - I'll work with engineering to narrow down exactly what ports would need to be open both ways.

Thanks,
Michael

**Comment by netapp-mwallis** [comment]
Hi Sean - I've removed the bidirectional recommendation after consulting with some SMEs in engineering.

**Comment by scaleoutsean** [comment]
Thank you, great! Feel free to close this if there's nothing else on your side.

**Comment by netapp-mwallis** [comment]
Hi Sean - I'm still waiting to hear back from the experts on the whitelisting steps.  We're going to break that out into a separate task, for one, but I'd like to get their input on your idea of using the HCC UI instead.  Will update as soon as I hear back.

**Comment by netapp-mwallis** [comment]
Reached out again to engineering for help with this.  Awaiting response.

**Comment by netapp-mwallis** [comment]
Hi Sean,
Per engineering, the logs are not a reliable way to see what URLs should be allowed.  The most consistent way to determine this is with a tool such as wget. Another option would be using the web browser's developer tools - you can capture all network traffic this way, but this varies from browser to browser, and version to version.  Using Wget is probably simpler process than capturing traffic or individual packets with Wireshark or a similar tool.
