### ISSUE TITLE
Port requirements table

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#117]
Page: [Required network ports](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

- This is wrong, most are outbound only "All ports are TCP unless stated otherwise, and should be open bidirectionally"
- Please add a 'direction' column to be clear about each relationship
- Add mNode > BMC/IPMI connectivity that's required enable Compute Health Checks to work (current HCC version)

**Comment by netapp-dbagwell** [comment]
Thanks Mark for your feedback. This appears to be a duplicate of comment #118. Closing this request and will address the same suggestions in #118.

**Comment by markjsmith2000** [comment]
Thanks Dave. I got an error on my first submission so I thought it had failed to submit, hence the duplicate.
