### ISSUE TITLE
Network Port requirements

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#118]
Page: [Required network ports](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

- This is wrong, most are outbound only "All ports are TCP unless stated otherwise, and should be open bidirectionally"
- Please add a 'direction' column to be clear about each relationship
- Add mNode > BMC/IPMI connectivity that's required enable Compute Health Checks to work (current HCC version)

**Comment by netapp-dbagwell** [comment]
Thanks for your feedback, Mark. We're looking into your suggestions now.

**Comment by netapp-mwallis** [comment]
The "should be open bidirectionally" requirement has been removed from this topic, and management node to BMC communication has been added as well. These changes will go live at the end of this month.
Thanks,
Michael

**Comment by netapp-dbagwell** [comment]
Hi Mark. Changes are now live: https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html
Thanks again for your feedback. 
Dave

**Comment by markjsmith2000** [comment]
Thanks Dave. I have submitted additional feedback as follows:


  *   For the source ‘Baseboard management controller (BMC)’ please update this to state which BMC it’s referring to. Is this storage node BMC/IPMI, compute node BMC/IPMI or both?
  *   Compute node BMC should read ‘Compute node BMC/IPMI’

Regards
Mark
