### ISSUE TITLE
Storage node firmware upgrades are separate now - add as step after Element upgrade

### ISSUE THREAD

**Issue by hubertjp** [NetAppDocs/hci#119]
Page: [Upgrade your NetApp HCI system for version 1.8](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_all.html)

Storage node firmware upgrades are separate now - add as step after Element upgrade
Step 4 - option B should become Step 5, and re-number the steps after.

**Comment by netapp-dbagwell** [comment]
Hi. Thanks for your feedback. Step 4 is written as a choice to either (a) perform both a full Element software and storage firmware upgrade, or (b) perform a storage firmware only upgrade. If step 4B were to become step 5, the user would be performing storage firmware upgrades in consecutive steps. Let me know if there's something I'm missing.

**Comment by hubertjp** [comment]
Storage node firmware updates are now being released outside of Element OS / NDE releases - so even after an Element Upgrade, the storage firmware can be upgraded.
Which is why I suggested 4b become step 5, as we should no longer assume an Element upgrade includes the latest storage node FW.

Jeff

**Comment by netapp-dbagwell** [comment]
Thanks Jeff for clarifying. We'll work this fix into our next release. It will also be fixed here: https://docs.netapp.com/us-en/hci/docs/task_sf_upgrade_all.html

**Comment by netapp-dbagwell** [comment]
Hi Jeff. Changes are live: 
https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_all.html
https://docs.netapp.com/us-en/hci/docs/task_sf_upgrade_all.html
Thanks for feedback!
