### ISSUE TITLE
BMC amendments

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#121]
Page: [Network port requirements](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

•	For the source ‘Baseboard management controller (BMC)’ please update this to state which BMC it’s referring to. Is this storage node BMC/IPMI, compute node BMC/IPMI or both?

•	Compute node BMC should read ‘Compute node BMC/IPMI’

Regards
Mark

**Comment by netapp-mwallis** [comment]
Hi Mark,

Thanks for catching this.  These "Baseboard management controller (BMC)" lines are actually duplicate information that we will remove in the next documentation hotfix.  Along with that change, we'll make sure to note BMC/IPMI in the remaining lines as well.  

Thanks,
Michael

**Comment by netapp-mwallis** [comment]
Hi Mark, this issue should be resolved now for both counts.  Thanks!
