### ISSUE TITLE
mNode>vCenter for VCP registration

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#122]
Page: [Network port requirements](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

The port table shows that vCenter (Source) to mMode (Destination) on port 9443 is required for VCP registration, but I believe this should be reversed (mNode>vCenter) or possibly bi-directional.

Regards
Mark

**Comment by netapp-dbagwell** [comment]
Thanks Mark for the additional feedback. I'll reach out to the VCP team for clarification.

**Comment by netapp-dbagwell** [comment]
Hi Mark. A second entry in the table for vCenter > mNode has been added to clarify the need to open port 9443 bi-directionally for VCP registration. 
Page: [Network port requirements ](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)
We appreciate the feedback.
