### ISSUE TITLE
Compute firmware upgrade via USB instructions

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#126]
Page: [Upgrade compute node firmware](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html)

This page explains how to upgrade the firmware on a compute node and is linked from https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/Compute_Firmware_Bundle/downloads

In the section, "Use a USB drive with the latest firmware image downloaded" it gives the following instructions:

1. Browse to the NetApp software downloads page, click NetApp HCI, and click the download link for correct version of NetApp HCI.
2. Accept the End User License Agreement.
3. Under the Compute and Storage Nodes section, download the compute node image.
4. Write the raw contents of the compute node RTFI image to a USB thumb drive with at least 32GB capacity (using dd or Etcher).

If my understaning is correct, you don't RTFI a compute node which is already part of an ESXi cluster using the compute node ISO. Instead, you boot from the compute node firmware ISO (compute-firmware-2.27.1-12.3.51.iso) which has been written to a flash drive using Etcher.

**Comment by netapp-amitha** [comment]
Hi Mark, thank you for the comment. We are verifying with engineering, and will report back as soon as we have an update.

**Comment by netapp-amitha** [comment]
Hi Mark, your understanding is correct about the RTFI. I will make the changes we discussed over email to make the terminology consistent across the topic. Thanks!

**Comment by markjsmith2000** [comment]
Great, thanks for letting me know.

Mark

**Comment by netapp-amitha** [comment]
@markjsmith2000 closing out this issue. The changes we discussed on email are published. Please let us know if further changes are needed. Thank you very much for your feedback and helping us improve our content.
