### ISSUE TITLE
Link to verify driver and firmware compatibility should go to IMT, not the KB with NDE included FW versions.

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/hci#129]
Page: [Upgrade compute node firmware](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html)

This link for the driver and firmware compatibility - should go to the IMT support matrix: https://mysupport.netapp.com/matrix, not the NDE included-versions KB.  That KB references drivers/firmware already installed - when the user needs to check future compatibility when upgrading.  Sometimes the IMT lags behind releases - so I would also add a note to review the compute firmware release notes.
--
What you’ll need
Compute drivers: You have upgraded your compute node drivers. If compute node drivers are not compatible with the new firmware, the upgrade will not start. See this **KB article** for driver and firmware compatibility information.
--

**Comment by netapp-mwallis** [comment]
Hi Jeff, 

Thanks for pointing this out.  I'll assign this one to myself and make this change - more info for the customer is always better. This change will go out with the next scheduled doc hotfix. Thanks! --Michael

**Comment by netapp-mwallis** [comment]
Hi Jeff,

http://vmwvatapp01-stg.corp.netapp.com/hci_hotfix_mw_fqdn_doc-3157/us-en/docs/task_hcc_upgrade_compute_node_firmware.html

Can you check the above link with the changes to that requirement, and let me know if this is what you had in mind?  Thanks!

**Comment by netapp-mwallis** [comment]
Closing with approval from Jeff.
