### ISSUE TITLE
Missing 2-cable networking changes

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/hci#132]
Page: [Supported networking changes](https://docs.netapp.com/us-en/hci/docs/task_nde_supported_net_changes.html)

Only two tables for 6-cable networking changes are listed for H300E, H500E, H700E and H410C compute nodes (VDS and VSS) - it's missing the 2-cable networking changes table.  (Should be a total of 3 tables)
See the previous version here for 1.7P1:  https://docs.netapp.com/hci/topic/com.netapp.doc.hci-ude-17P1/GUID-A1B10816-CE4D-44DD-B914-F36FEA421D00.html

**Comment by netapp-amitha** [comment]
@jhubert-netapp thank you for the feedback. We will add the missing 2-cable networking info and update this topic at the earliest. Thanks again! I'll update you when the updates are live.

**Comment by netapp-amitha** [comment]
@jhubert-netapp updates are now available. I'm closing this issue out. Please reach out if you have further comments. Thanks!
