### ISSUE TITLE
Add list of post-deployment tasks on the summary page.

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/hci#133]
Page: [Post-deployment tasks](https://docs.netapp.com/us-en/hci/docs/concept_nde_post_deployment_overview.html)

Can we add a list of the post-deployment tasks to this summary page?

Post-deployment tasks overview
Supported networking changes
Disable the smartd service on NetApp HCI compute nodes
Keep VMware vSphere up to date
Install GPU drivers for GPU-enabled compute nodes
Configure Fully Qualified Domain Name web UI access
Access NetApp Hybrid Cloud Control
--
I would also add -
- Move ESXi scratch to shared storage: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_reduce_wear_on_the_boot_drive_of_a_Netapp_HCI_compute_node
- Check for HCC and HCI Updates:  https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_all.html

**Comment by netapp-mwallis** [comment]
Hi Jeff, thanks for these suggestions.  We'll add the list of tasks and investigate the best way to migrate the KB content to GitHub.  I'll update when it's done. There's an existing ticket on the "reducing wear of boot drive" issue: DOC-2509. DOC-3200 is open for the post-deployment TOC additions, and DOC-3201 for the KB migration.
Thanks! -- Michael

**Comment by netapp-mwallis** [comment]
Hi Jeff, here's an update on this issue:
- DOC-3200: This is complete - the list of post-deployment tasks is now part of the summary page.
- DOC-2509: Product management would like to keep the "reduce wear on boot drive" KB article in place, as the Support team uses it. This will eventually be done automatically.  For now, we're going to link from the main documentation to this KB article.  I'm determining where this will go right now and will update here when complete.
- DOC-3201: This is on hold as we simply don't have the bandwidth right now to migrate these articles (lots of doc movement from older sources to the newer platform right now). 

Thanks,
Michael

**Comment by netapp-mwallis** [comment]
Hi Jeff,

DOC-2509 is complete - I've added it as a post-deployment task in the HCI docs. Closing this issue and will revisit DOC-3201 when we have bandwidth.

Thanks,
Michael
