### ISSUE TITLE
Compute Firmware Bundle Instructions

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#138]
Page: [Upgrade compute node firmware](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html)

These statements are both incorrect because this page gives instructions for installing the Compute Firmware Bundle:

"For compute node image 12.0: Use a USB drive with the latest compute node firmware ISO downloaded"
"For compute firmware 12.2.109: Use the Baseboard Management Controller (BMC) user interface (UI)"

It should not reference 12.0 or 12.2.109 as they are both Compute node image versions, not Compute Firmware Bundle versions. 

For reference, the Compute Firmware Bundle version is 2.27 and the download page for it is https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/Compute_Firmware_Bundle/downloads

The statements should be corrected to say:

"Use a USB drive imaged with the compute node firmware bundle ISO"
"Use the Baseboard Management Controller (BMC) user interface (UI) to mount the compute firmware bundle ISO"

Regards
Mark

**Comment by netapp-mwallis** [comment]
Hi Mark, thanks for this feedback.  We'll correct this in the next documentation update, which should be in early December. For reference, I've opened DOC-3214 (https://jira.ngage.netapp.com/browse/DOC-3214) to track this issue.

Thanks,
Michael

**Comment by netapp-mwallis** [comment]
Hi Mark,
This change is going live this evening. Apologies for the delay, and thanks again for the feedback.

--Michael
