### ISSUE TITLE
ESXi 7 compatibility

### ISSUE THREAD

**Issue by markjsmith2000** [NetAppDocs/hci#142]
Page: [Compute Firmware Bundle 2.27 Release Notes](https://docs.netapp.com/us-en/hci/docs/rn_compute_firmware_2.27.html)

This page has a section which says the Mellanox driver is compatible with ESXi driver version 4.19.16.1 but doesnt include a link to where I can download this ESXi driver. Any idea where I download ESXi driver v4.19.16.1 referenced in the 2.27 release notes? 

The most recent driver available to download on NSS is 4.17.15.16  - which is the version in the Hx00E/H410C ESXi 6.7 zip file: https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/ESXI_drivers/downloads

**Comment by netapp-mwallis** [comment]
Hi Mark,
Thanks for your question - not sure how this was missed in our docs.  I'm asking our web team what the correct link to use is and will get you that as soon as they respond. I'll also revise the release notes to have this information going forward.
Thanks,
Michael

**Comment by markjsmith2000** [comment]
Hi Michael,

The ESXi drivers download page doesn’t actually include a download which includes 4.19.16.1 so I’ll be interested to hear what the web team says. 😊

I’d like to see the 7.0 ESXi drivers added to this<https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/ESXI_drivers> page, then you can simply reference this URL.

Mark

**Comment by netapp-mwallis** [comment]
Hi Mark, 

I checked with the experts regarding posting the ESXi 7.0 drivers on our download site. Right now, if  you are running vSphere 7.0, you need to use vSphere Update Manager to update to the latest version of the ESXi drivers.  In the future, the goal is to include these drivers in NetApp HCI bundles for upgrade via HCC. I'll update the docs to make this more clear for 7.0 users.   Apologies for the confusion - let me know if you have any questions.

Thanks,
Michael

**Comment by netapp-mwallis** [comment]
Note - The documentation now refers to the driver upgrade instructions, which have the correct path of updating via vSphere Update Manager.  Closing this request.
