### ISSUE TITLE
Add port 623 UDP 

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/hci#143]
Page: [Network port requirements](https://docs.netapp.com/ja-jp/hci/docs/hci_prereqs_required_network_ports.html)

Add Port 623 UDP - Required between management Node and Compute IPMI/BMC - Remote Management Control Protocol (RMCP) port.  Needed for HCC Compute Firmware upgrade functionality.

**Comment by netapp-dbagwell** [comment]
Thanks for your feedback, Jeff. I've opened a doc request to address this for our next doc update.

**Comment by netapp-dbagwell** [comment]
Added port 623 info to [ports](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html) article. Compute firmware topic refers to this article as a prereq.
