### ISSUE TITLE
Missing optional BMC/IPMI ports for H410C and H615C

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#150]
Page: [Network port requirements](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

For H610S there's a [KB](https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/Which_ports_needed_for_Quanta_BMC_console_redirection) but I think that info should be in public facing docs because it is required for pre-deployment planning. 

The same should apply to H615C and H610C (I suppose), so if all three share unique requirements, those could be put in a separate, smaller table.

The H410C is missing ports required for "mount image" as well as KVM (5900), maybe some other too (this info is available in h/w vendor IPMI/BMC documentation). Ports that are common (with H600 series) could be added to the existing large table, and if H410S and H410C have unique ports, those could be added in a new, small table.

**Comment by amgrissino** [comment]
Thanks, @scaleoutsean for your careful review and feedback. We will work resolving this and let you know.

**Comment by ntap-bmegan** [comment]
This issue will be closed on tues 30 aug 2022 due to lack of activity within the last 30 days. @scaleoutsean - If you believe that the original problem persists, please comment in this issue to keep it open for further review.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - Apologies for the delay in responding to this issue. I've created [DOC-4471](https://jira.ngage.netapp.com/browse/DOC-4471) to track this request so I can close this issue. I'll keep you updated via the doc ticket. Thanks!

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - I've reached out to our SME for feedback on how best to update the documentation. To get a better understanding, when you get a chance, could you provide a more specific list of the ports that you used or know about?

**Comment by scaleoutsean** [comment]
See at the very top, the KB link contains a list of all the services, protocols and ports that may be required to connect to IPMI - SSH, Remote Console, etc. 

In many cases people don't have strong firewalls on internal management networks, but sometimes they do, and if ports aren't open then various operations (including firmware upgrades) may fail.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - Thank you. To help narrow down the list, could you provide a specific list of commonly used ports and also specify the platform. For example, for H410C nodes:
- Port 623 (UDP) for BMC IPMI
- Port 5900 (TCP) for remote console
Thanks again!

**Comment by scaleoutsean** [comment]
I'd say let's just mention two that most usres open:

* IPMI (TCP/UDP) 623
* HTTPS (TCP) 443

For the rest we could say "Please check the NetApp KB for other, less frequently used services."

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - Looks good, thank you.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - Thanks for providing this detail. I'll work with the engineer to get the documentation updated as soon as possible.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - Could you verify if the following table contains the information that needs to be added, thanks:
![image](https://user-images.githubusercontent.com/77334475/197792305-c9fc6f6d-b916-48d6-adf9-d5fb48965295.png)

**Comment by netapp-pcarriga** [comment]
Great, thanks @scaleoutsean . I'll update you here when the updates are published.

**Comment by netapp-pcarriga** [comment]
@scaleoutsean - The 443 and 623 UDP port information for the H410 and H600 series have been add to the "Network port requirements" pages in the NetApp HCI and Element software documentation:
["Network port requirements" ](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)
https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html
Thanks again for your feedback and apologies again for the delay with getting this update documented.
Closing this issue.
