### ISSUE TITLE
Changes requested to the existing HCI H410S node replacement document

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/hci#161]
Page: [Replace H410S nodes](https://docs.netapp.com/us-en/hci/docs/task_hci_h410srepl.html)

The Net2 team received the following feedback regarding the HCI H410S node replacement document that we are also using:
1. The AP gives 3 scenarios for 3 different HCI versions when adding the new node into the system. Nowhere does it actualy state where the HCI version can be found.
2. There was also a requirment for an RTFI, not mention of this in the AP, and the download was a large file, something that adds to the time on site considerably.
3. The final configuration is using a TUI, again no mention of how in the AP, and the TUI is not intiuitive, a guide is required.

I can provide additional information regarding RTFI, and the TUI, including screen captures. Please reach out to me as necessary.

**Comment by netapp-amitha** [comment]
Hi Jamie, thanks for sharing the feedback. I'll work with you for items 2 and 3. I'm not sure I understand the comment in item 1. Under the "Add storage node to the cluster" section, we have 3 subheadings indicating the HCI versions and the steps for each versions. If you have any more information for item 1, please let me know. Thanks.

**Comment by netapp-amitha** [comment]
@JamieLove-Net2 here is the Jira ticket for this issue: https://jira.ngage.netapp.com/browse/DOC-3313

**Comment by netapp-amitha** [comment]
Tackling this issue in an email thread. Will update issue with info.

**Comment by netapp-amitha** [comment]
Closing this issue because we have a Jira issue for tracking it and an associated email thread where we are chasing the info needed.
