### ISSUE TITLE
Update compute node drivers

### ISSUE THREAD

**Issue by netapp-dvasiliu** [NetAppDocs/hci#162]
Page: [Update compute node drivers](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_drivers.html)

Great job to all first of all!

This is just an observation, but when reviewing this for customers steps, to me its not clear since it does not flow.  If its wrong, please just ignore.

These steps are all valid until one in this snip it:
=========================
Steps

    Browse to the NetApp HCI software downloads page and click the download link for correct version of NetApp HCI.

    Select Compute_Firmware_Bundle from the drop-down list.

    Accept the End User License Agreement.

    Under the Driver Packages for VMWare ESXi heading, download the driver package for your node type and ESXi version.
==========================
-> this last part: 
Under the Driver Packages for VMWare ESXi heading, download the driver package for your node type and ESXi version.
-> Since its in BOLD, makes me think i'm looking for that title and stated "Under the". --> I don't see this section.
-> Now on the right side, there is a one liner with 'Link' to the esxi drivers.
-> My opinion, just does not flow.

A better solution: in the second line:
  Select Compute_Firmware_Bundle from the drop-down list.  
-> instead of compute_firmware_bundle selection, select "ESXI_drivers" 
-> this takes you to same step your trying to achieve.

Let me know if this make sense. For any questions, please let me know at dvasiliu@netapp.com

**Comment by netapp-amitha** [comment]
Hi @netapp-dvasiliu, thanks for the comment. It does look like Step 4 is misleading. We will fix it to make the content flow better. We will send you the updated steps before we publish it externally.

**Comment by netapp-amitha** [comment]
@netapp-dvasiliu Fixed. Thanks! The update is live https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_drivers.html
Please reach out if further changes are required. Thanks again!

**Comment by netapp-dvasiliu** [comment]
Hello @netapp-amitha,
Thank you for your feedback and looks great. Was all tied up and i missed your prior update.  As always, great job!
