### ISSUE TITLE
formatting issues with URLs

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/hci#168]
Page: [Management node overview](https://docs.netapp.com/us-en/hci/docs/task_mnode_work_overview.html)

Current mNode UI reference:

https:// [mNode IP}:442

Should be:

https://[mNode IP]:442

(Assuming that square brackets are the standard, please swap out curly brace for square brace and remove the extra whitespace after '//')

Also, please use square brackets for the mixed brackets in https://[mNode IP}/mnode.

**Comment by amgrissino** [comment]
Thanks @ddansf for the catch. We're on it.

**Comment by amgrissino** [comment]
Created Jira doc ticket DOC-3336

**Comment by netapp-amitha** [comment]
This is done: https://jira.ngage.netapp.com/browse/DOC-3336
