### ISSUE TITLE
change proxy_ip_or_hostname

### ISSUE THREAD

**Issue by raoulschaffner** [NetAppDocs/hci#171]
Page: [Configure a proxy server](https://docs.netapp.com/us-en/hci/docs/task_mnode_configure_proxy_server.html)

from my experience, it takes a reboot of the management node to fully apply a changed proxy_ip_or_hostname address. unless you reboot the node, both the old and the new proxy addresses are being used, probably by various subsystems of the node.

**Comment by netapp-dbagwell** [comment]
Thanks for your feedback, Raoul. We'll look into improving the content on that page for the next doc release.

**Comment by netapp-dbagwell** [comment]
@raoulschaffner Test was able to switch from one proxy server to the next properly using a recent build of management services without mNode reboot. Can we get more information on the request to ensure it's not environment issue?

**Comment by raoulschaffner** [comment]
@netapp-dbagwell sure. shall i send my config and my findings to a specific mail address? or does this info suffice:
- hci 1.8p1 with element os 12.2.0.777 and firmware bundle 2.76.8.0
- mnode mgmt service 2.17.56

**Comment by netapp-dbagwell** [comment]
Thanks again for the feedback. We weren't able to determine a situation where an mnode reboot would be required. However, a note has been added after the last procedural step indicating a reboot might be necessary depending on the environment:
https://docs.netapp.com/us-en/element-software/mnode/task_mnode_configure_proxy_server.html
https://docs.netapp.com/us-en/hci/docs/task_mnode_configure_proxy_server.html
