### ISSUE TITLE
Include link to Witness Node OVA download in the redeploy instructions

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/hci#181]
Page: [Replace H410C nodes](https://docs.netapp.com/us-en/hci/docs/task_hci_h410crepl.html)

In step 4 in https://docs.netapp.com/us-en/hci/docs/task_hci_h410crepl.html#redeploy-witness-nodes-for-two-and-three-node-storage-clusters, we're assuming that the VM Template is present in the vCenter environment. If it's not (e.g., if the customer has deleted the template), they'll need to download the .ova image and redeploy it.

Here's the download link: https://mysupport.netapp.com/site/products/all/details/netapp-hci/downloads-tab/download/62542/WN_12.0/downloads

**Comment by netapp-amitha** [comment]
@ddansf Dan, thanks for the feedback. I confirmed with engineering that users will need to contact Support to get the Witness Node ova image and redeploy it. Even if they have the template available, it's suggested to still have Support guidance to help set it up. 
I will update the topic to say this. Thanks!

**Comment by netapp-amitha** [comment]
https://jira.ngage.netapp.com/browse/DOC-3450 to track the fix.

**Comment by netapp-amitha** [comment]
@ddansf Added note in this topic: https://docs.netapp.com/us-en/hci/docs/task_hci_h410crepl.html#redeploy-witness-nodes-for-two-and-three-node-storage-clusters I'm closing this issue. Please let us know if you have further comments. Thanks.
