### ISSUE TITLE
HCI Documents in Japanese

### ISSUE THREAD

**Issue by yukakou** [NetAppDocs/hci#187]
Page: [NetApp HCI のドキュメント](https://docs.netapp.com/ja-jp/hci/index.html)

When I select Japanese from the language filter on HCI docs, there are only 2 sentences that are in English. I can see 2 titles in Japanese in the left pain, but clicking those titles don't work. Can you please check and fix?

**Comment by netapp-dbagwell** [comment]
Hi Yukakou. I've reported this issue to the localized content owners. Will update this ticket again when there is progress. Thanks for your feedback.

**Comment by netapp-dbagwell** [comment]
Per feedback from https://github.com/NetAppDocs/jekyll-harmony/issues/11

It has now been fixed and our procedure has been updated. Marking as closed.
https://docs.netapp.com/ja-jp/hci/

The untranslated lead statement is a separate issue being tracked.
