### ISSUE TITLE
enabling mnode ssh via curl command doesn't work

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/hci#191]
Page: [Manage SSH functionality on the management node](https://docs.netapp.com/us-en/hci/docs/task_mnode_ssh_management.html)

These curl instructions don't work. For starters, the https://<managementNodeIP>/mnode/settings/ endpoint doesn't seem to exist; rather, when you navigate to the settings section in swagger, it's more like https://<mnode_ip>/mnode/1/#/settings (at least on a 12.2 mNode with mgt services 2.13; mnodes on 2.18 seem to use https://<mnode_ip>/mnode/2/services).

In addition, the use of the Bearer <ID> is confusing and needs to be defined more clearly. As in, what settings endpoint to run a GET against to obtain the token and how to substitute it into the curl command.

This might be of assistance on the latter point: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/Use_curl_to_automate_swagger

On the former point (which endpoint URL to use), we need to find out what the endpoints are for various management services releases (e.g., which uses /mnode/1 vs. /mnode/2 structures?) to clarify.

Also, the '--insecure' option for curl is likely necessary for some environments.

Lastly, it may be useful to mention that the tokens expire (e.g., you need to use it within 5 minutes in the context of a curl command or auth will fail).

**Comment by netapp-amitha** [comment]
@ddansf Thanks for the feedback. We have created this Jira issue to track the updates: https://jira.ngage.netapp.com/browse/DOC-3555

**Comment by netapp-dbagwell** [comment]
Tracking with DOC-3555. Work is in progress. Closing public request.
