### ISSUE TITLE
'Use API to run Element storage health checks prior to upgrading storage' steps are confusing and easier options are available

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/hci#195]
Page: [Run Element storage health checks prior to upgrading storage](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_element_prechecks.html)

The current documentation around running health checks in Swagger is more complicated than it needs to be.

Using the inventory API as documented requires parsing through a large json file to locate the storage id.

Instead, using GET /assets from https://mnode_ip/mnode is a lot easier to parse through and customers use /mnode more frequently. See: https://kb.netapp.com/Advice_and_Troubleshooting/Hybrid_Cloud_Infrastructure/NetApp_HCI/How_to_monitor_upgrades_and_health_checks_in_HCC_using_swagger

So basically the ask is to use /mnode and /storage instead of /inventory/ and /storage.

Also, the verification section below is inaccurate in that you cannot see the KB's referenced in 'Go to the specific KB article listed for each issue or perform the specified remedy.' if you're using the GET ​/health-checks​/{healthCheckId} endpoint (which only shows a summary response). To actually see the KB recommendations mentioned here, you need to use the GET ​/health-checks​/{healthCheckId}/log endpoint that shows the full log output.

As written:
--
Verify the results of the health checks:

Click GET ​/health-checks​/{healthCheckId}.

Click Try it out.

Enter the health check ID in the parameter field.

Click Execute.

Scroll to the bottom of the response body.

If the message return indicates that there were problems regarding cluster health, do the following:

Go to the specific KB article listed for each issue or perform the specified remedy.

If a KB is specified, complete the process described in the relevant KB article.

After you have resolved cluster issues, run GET ​/health-checks​/{healthCheckId} again.

--

**Comment by netapp-dbagwell** [comment]
Thanks, Dan. I've created a doc request to address this.

**Comment by netapp-dbagwell** [comment]
This request is in production phase and being tracked by DOC-3599. Please see the ticket for updates on progress. Closing public request.
