### ISSUE TITLE
“netappdownloads.jfrog.io:443” is missing from the "Network Port Requirements" page

### ISSUE THREAD

**Issue by pborkstrom** [NetAppDocs/hci#196]
Page: [Network port requirements](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

Hi, 

I have a customer that requires specific firewall rules for mNode/HCC functionality.  The customer configured the proxy/firewall rules according to the NetApp documentation, and we were unable to download update tools and firmware.  During the customer's troubleshooting, they discovered “netappdownloads.jfrog.io:443” was blocked.  Once they unblocked that, the downloads were working.  That URL/port is not in the NetApp HCI firewall rules documentation. 

Regards,

Phil Borkstrom
borkp@netapp.com

**Comment by netapp-amitha** [comment]
Hi Phil, thanks for the feedback. We have created a Jira issue to track this. We will confirm with engineering and make the updates. https://jira.ngage.netapp.com/browse/DOC-3604

**Comment by netapp-dbagwell** [comment]
The change is now live: https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html
