### ISSUE TITLE
Add inventory refresh step between steps 9 and 10

### ISSUE THREAD

**Issue by ddansf** [NetAppDocs/hci#197]
Page: [Update vCenter and ESXi credentials](https://docs.netapp.com/us-en/hci/docs/task_hci_credentials_vcenter_esxi.html)

In the field, we've found that waiting 15 minutes (step 10) after making the preceeding updates in swagger does not always work. In discussing this with Adam Kittel, one improvement we could add is to refresh the inventory service after making the credentials updates.

So, after current step 9 and before current step 10 / future step 11:

10. Navigate to https://<mNode_ip>/inventory/1/
a. Click Authorize or any lock icon and complete the following:
-Enter the NetApp SolidFire cluster administrative user name and password.
-Enter the client ID as mnode-client.
-Click Authorize to begin a session.
-Close the window
b. From the REST API UI, click GET /installations
c. Click 'Try it out'
d. set the refresh description dropdown to 'true'
e. Click 'Execute'
f. Validate that the response is HTTP 200

(then move on to the wait 15 minutes step that's already documented as the last step)

If all of the above are done and the new credentials still aren't reflecting, a scheduled reboot of the mNode will force an update.

**Comment by netapp-dbagwell** [comment]
Thanks, Dan! Created a doc bug to improve the content and added you as reporter.

**Comment by netapp-dbagwell** [comment]
Closing the public request. Doc improvement DOC-3605 is in the queue and will be corrected at earliest convenience.
