### ISSUE TITLE
Test comment

### ISSUE THREAD

**Issue by netapp-lhalbert** [NetAppDocs/hci#199]
Page: [NetApp HCI Documentation](https://docs.netapp.com/us-en/hci/index.html)

Wanted to see if adding a comment can be seen by anyone else who is viewing and commenting on the site.

Whoever receives this comment, would you please let me know? You can email lhalbert@netapp.com or use whatever GitHub process exists. Thank you.

**Comment by netapp-amitha** [comment]
Responded to Lisa on Teams.
