### ISSUE TITLE
wrong workflow

### ISSUE THREAD

**Issue by Kenneth-borg** [NetAppDocs/hci#209]
Page: [Replace H610C and H615C nodes](https://docs.netapp.com/us-en/hci/docs/task_hci_h610ch615crepl.html)

The workflow is wrong as we cant install the gpu drivers until after we added the new node to the vcenter cluster. 

current:
Prepare to replace the node
Replace the node
Install the GPU drivers
Add the node to the cluster

should be:
Prepare to replace the node
Replace the node
Add the node to the cluster
Install the GPU drivers if compute node has a GPU card

**Comment by netapp-pcarriga** [comment]
Hi Kenneth,
This issue is now fixed. Thanks! The update is live https://docs.netapp.com/us-en/hci/docs/task_hci_h610ch615crepl.html
Please reach out if further changes are required. Thanks again!
