### ISSUE TITLE
Remove "behind the scenes" phrasing

### ISSUE THREAD

**Issue by netapp-dbagwell** [NetAppDocs/hci#22]
Page: [What happens behind scenes with NetApp Fabric Orchestrator and NetApp HCI](https://docs.netapp.com/us-en/hci/docs/concept_behind_the_scenes_fo.html)

Can we please replace *What happens behind scenes* and phrasing like this throughout HCI GitHub docs with something less colloquial and easier to translate?

**Comment by amgrissino** [comment]
Changed the titles in the topics and left nav for localization ease. Thanks again, Dave. Closing this.
