### ISSUE TITLE
Step 7 does not give specific steps to Import the driver offline bundle file for the compute nodes into the Patch Repository.

### ISSUE THREAD

**Issue by jorimp** [NetAppDocs/hci#236]
Page: [Update compute node drivers](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_drivers.html)

Customers are having issues figuring out step 7. It says to upload the bundle to the patch repository, but does not tell you how.

For ESXi 6.7, I found the steps to be 

1. Click on the "Updates" tab.
2. Click "UPLOAD FROM FILE".
3. Browse to the offline bundle that was previously downloaded, then click IMPORT.

**Comment by netapp-pcarriga** [comment]
@jorimp Thank you for your feedback and helping us improve our customer documentation. 
We'll get these steps verified and added to the documentation.
Thanks!

**Comment by netapp-pcarriga** [comment]
@jorimp The HCI documentation is now updated with the bundle installation instructions for VMware ESXi 7.0 and ESXI 6.x. 
The documentation updates are complete so closing this ticket. 
Thanks again for your feedback!

**Comment by jorimp** [comment]
Awesome! Nice work!
