### ISSUE TITLE
Please add a caution not to use HCI1.x image to ugprade firmware.

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/hci#243]
Page: [Upgrade compute node firmware](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html)

We switched behaviour to retain boot.epo and partition ESXi is installed on HCI1.6 for upgrading compute firmware using RTFI  image. Later, we released compute firmware bundle.  Then, we switched to old behaviour again at HCI 1.8P1 (PE-9474).
Please add a caution to use "compue firmware bundle" to upgrade compute node firmware, and not to use RTFI image.

**Comment by netapp-pcarriga** [comment]
@hayatokurahashi Thank you for your feedback and helping us improve our customer documentation.
We'll get your feedback verified and then update the documentation.
Thanks!

**Comment by netapp-pcarriga** [comment]
@hayatokurahashi We have updated the compute node firmware upgrade section in the NetApp HCI documentation in response to your feedback: https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html
Thank you again for helping us improve NetApp customer documentation and apologies for any inconvenience caused.
