### ISSUE TITLE
HCI 1.9P1 does not include Element 12.3.2

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/hci#245]
Page: [What’s new in NetApp HCI](https://docs.netapp.com/us-en/hci/docs/rn_whatsnew.html)

"NetApp HCI 1.9P1 includes Element 12.3.2 for storage clusters."

HCI 1.9P1 does not include Element 12.3.2, it includes 12.3.1.  The user would have to download the Element 12.3.2 ISO separately for the storage nodes.

**Comment by netapp-pcarriga** [comment]
@jhubert-netapp - thank you for your feedback!.
I've created [DOC-4248](https://jira.ngage.netapp.com/browse/DOC-4248) to track this update.

**Comment by netapp-pcarriga** [comment]
@jhubert-netapp The documentation is now updated to clarify that Element 12.3.1 is included in HCI 1.9P1 and includes the circumstances for upgrading to Element 12.3.2.
Thanks again for your feedback.
Closing this issue.
