### ISSUE TITLE
It seems SFB 2.150 changed nothing compared with 2.146, please verify and update this info if nothing has changed.

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/hci#254]
Page: [Storage Firmware Bundle 2.150 Release Notes](https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.150.html)

It seems SFB 2.150 changed nothing compared with 2.146, please verify and update this info if nothing has changed.
otherwise, the customer may ask what's the difference between 2.150 and 2.146

**Comment by netapp-yvonneo** [comment]
Hi Xinwei-Wang, 

Thanks for your feedback. We will look into it and determine how best to address it. 

Yvonne O’Sullivan
Information Engineering (IE) Content Services

**Comment by netapp-yvonneo** [comment]
Hi Xinwei-Wang,

I've added details of the critical bug that's fixed in this version 2.150. See the updated details here: https://docs.netapp.com/us-en/hci/docs/rn_storage_firmware_2.150.html.

Thanks again for your feedback. Closing this issue. 

Regards,
Yvonne
