### ISSUE TITLE
If the upgrade begin automatically? or "[Begin Upgrade]" button will be showing up?

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/hci#257]
Page: [Update management services](https://docs.netapp.com/us-en/hci/docs/task_hcc_update_management_services.html)
Page: [Upgrade Element software](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_element_software.html)

The customer is confused about the above two pages if the upgrade is started automatically after the package is uploaded? or some button will be showing up? like [Begin Upgrade]..  Please add the related info to those pages..

As I checked when upgrading to the latest Management service, once uploading is completed the upgrade is started automatically, 
but for the element software or firmware, the "begin upgrade" button will be showing up...

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang Thank you for providing this feedback.
I'll investigate and, if required, update the documentation to provide the clarity.

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang - We've updated the documentation to clarity that if a management services package is manually uploaded, it will automatically start the upgrade: [Update management services](https://docs.netapp.com/us-en/hci/docs/task_hcc_update_management_services.html)
Thanks again for your feedback.
