### ISSUE TITLE
About the path for mNode upgarde

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/hci#260]
Page: [Upgrade a management node](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_management_node.html)

This page only describe mnode upgrade from 12.3.x to 12.5, while customer using 12.2, is that need to upgarde 12.3 first?
I think both 12.x can upgrade directed to 12.5 using the in-place upgrade mode. also this page written below means mnode from 12.0 can upgrade to 12.5 directly, if I'm right , could you change the version 12.3.x to 12.x ?  or add comment that all mNode on 12.0 and above can upgrade to 12.5 directly.

>>The management node you are intending to upgrade is version 12.0

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang - Thank you for your feedback and apologies for the confusion with the upgrades documentation.
I'll verify the upgrade sequence with a subject matter expert and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang - It's been confirmed by a SolidFire subject expert you can upgrade a management node directly from Element 12.0 to 12.5 and Element 12.2 to 12.5. You are **not** required to first upgrade to Element 12.3.x.
Thanks again for contacting us and please reach out with any further documentation queries.

**Comment by Xinwei-Wang** [comment]
@netapp-pcarriga Thanks for your check. Do we have plan to modify this on the Doc page?

**Comment by netapp-pcarriga** [comment]
@Xinwei-Wang - You're welcome and we were happy to investigate this query for you. However, at this point, we do not plan to update the Element 12.5 documentation.
