### ISSUE TITLE
Release notes should contain NEW vSphere 7.0 deployment support

### ISSUE THREAD

**Issue by jhubert-netapp** [NetAppDocs/hci#264]
Page: [What’s new in NetApp HCI](https://docs.netapp.com/us-en/hci/docs/rn_whatsnew.html)

**Comment by netapp-pcarriga** [comment]
@jhubert-netapp - Hi Jeff, thank you for your feedback. I've created [DOC-4457](https://jira.ngage.netapp.com/browse/DOC-4457) to track this update.

**Comment by netapp-pcarriga** [comment]
@jhubert-netapp - Hi Jeff, the new vSphere 7.0 deployment support has been added to the "[What's new](https://docs.netapp.com/us-en/hci/docs/rn_whatsnew.html#supported-versions-of-vmware-vsphere-updates)" section in the NetApp HCI 1.10 documentation. 
Thanks again for contacting us and helping us improve the customer documentation.
