### ISSUE TITLE
generate fr and de - 6399

### ISSUE THREAD

**Issue by netapp-gudugunti** [NetAppDocs/hci#278]
A localization admin will generate the French and German sites. 

### Site maintainers and mergers
Comment in this issue if you update the English site before the issue closes. No other action is required on your part.

**Comment by dmajones** [comment]
Sites (fr-fr& de-de) are up and running. Set permissions and BPR. 
Total TOT: 8 minutes.

**Comment by netapp-gudugunti** [comment]
Completed configs.

**Comment by dmajones** [comment]
@ntap-bmegan thanks for catching it. @netapp-gudugunti Thank you Ashwath!
