### ISSUE TITLE
Port missing

### ISSUE THREAD

**Issue by lowest21** [NetAppDocs/hci#283]
Page: [Network port requirements](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html)

You don't list UDP port 623 needs to be open between the mNode and the storage nodes BMC. This results in the error below.
admin@**** ~ $ sudo smc-sum -i *.*.*.* -u root -p calvin -c GetBmcInfo
Password:
Supermicro Update Manager (for UEFI BIOS) 2.5.0 (2020/07/22) (x86_64)
Copyright(C) 2013-2020 Super Micro Computer, Inc. All rights reserved.
................Checking connection.........................................
........................................................
........................................................
........................................................
........................................................
...............................
********************************<<<<<ERROR>>>>>*********************************
ExitCode                = 34
Description             = UDP connection error
Program Error Code      = 110.2
Error message:
        Failed reading socket from *.*.*.*:623 Read socket error code = 11
    Resource temporarily unavailable
********************************************************************************

**Comment by netapp-pcarriga** [comment]
Hi @lowest21, thank you for providing feedback and apologies for the inconvenience. I'll verify your feedback with a product engineer and provide an update here.

**Comment by netapp-pcarriga** [comment]
@lowest21 - We have updated the [Network port requirements](https://docs.netapp.com/us-en/hci/docs/hci_prereqs_required_network_ports.html) page with your request to include the UDP port 623 between the management node and the storage node BMC/IPMI. If you require further updates relating to this issue, please let me know by reopening this ticket. Thanks again for taking time to provide feedback.
