### ISSUE TITLE
documentation is too basic

### ISSUE THREAD

**Issue by ntap-johanneswagner** [NetAppDocs/hci#286]
Page: [Power off storage resources for a NetApp HCI system](https://docs.netapp.com/us-en/hci/docs/task_nde_hci_power_off_storage.html)

please compare with 
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Element_Software/How_to_gracefully_shut_down_and_power_on_a_NetApp_Solidfire_HCI_storage_cluster

there are several things to be aware off, especially that a simple browser refresh can shutdown the system again...

**Comment by netapp-pcarriga** [comment]
@ntap-johanneswagner HI Johannes, thanks for providing this feedback. I'll review your recommendations with the engineers and then update the documentation and this ticket.
