### ISSUE TITLE
Correct the typo under H300E/H500E/H700E 

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/hci#289]
Page: [Compute nodes](https://docs.netapp.com/us-en/hci/docs/fw_compute_nodes.html)

there are two rows under "H300E/H500E/H700E " with the typo of storage like the below, please correct it.

Storage Firmware Bundle 2.150.4 through NetApp HCI 1.10
Storage Firmware Bundle 2.146.2

**Comment by netapp-pcarriga** [comment]
Hi @Xinwei-Wang - Thank you for highlighting this. I'll update the documentation and also update you here when it's published.

**Comment by netapp-yvonneo** [comment]
Hi Xinwei-Wang,

The content has been updated, please see here: https://docs.netapp.com/us-en/hci/docs/fw_compute_nodes.html

Thank you for your feedback.
