### ISSUE TITLE
please add info for H300E/H500E/H700E in to the [Minimum BMC and BIOS versions:] talbe

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/hci#302]
Page: [Upgrade compute node firmware](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html)

there is no info for H300E/H500E/H700E in the talbe list of "Minimum BMC and BIOS versions:", please add it.

**Comment by netapp-yvonneo** [comment]
@Xinwei-Wang thanks for your feedback. The topic has been updated here: https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_compute_node_firmware.html  Closing this issue.
