### ISSUE TITLE
Please help to check if HCI release note need to be changed?

### ISSUE THREAD

**Issue by Xinwei-Wang** [NetAppDocs/hci#303]
Page: [Additional release information](https://docs.netapp.com/us-en/hci/docs/rn_relatedrn.html)

Some release note of HCI has the below description, but from the VMWare upgrade path checker (https://interopmatrix.vmware.com/Upgrade), there is no problem to upgrade ESXi 6.5U2/6.5U3 directly to 7.0,
also no problem for vCenter to direct upgrade from 6.5 to 7.0, is the below note need to be changed? or have some other reason can't upgrade directly? please check and reply ASAP since the customer is waiting for the answer. 

> Example:
> https://library.netapp.com/ecm/ecm_download_file/ECMLP2879274
> 
> NetApp HCI does not support a direct upgrade from vSphere version 6.5u2 to version 7.0. If you
> are upgrading from version 6.5u2, upgrade to vSphere version 6.7u3 first and then upgrade to
> version 7.0.
>

**Comment by netapp-pcarriga** [comment]
Hi @Xinwei-Wang, thanks for your feedback. I'll verify your observations with a product expert and update the documentation accordingly.

**Comment by Xinwei-Wang** [comment]
Thanks for checking. Could you share when this can be updated ? it will be released as another new link?
Please note multiple release not have this kind of description , updated all is necessary.

**Comment by netapp-pcarriga** [comment]
Hi @Xinwei-Wang, the update are in progress for all affected version of the NetApp HCI release notes. You will be able to access the updated version from the links on [this page](https://docs.netapp.com/us-en/hci/docs/rn_relatedrn.html#netapp-hci) and on the [NetApp Support](https://mysupport.netapp.com/documentation/productlibrary/index.html?productID=62542) site. I will update you here when these updates are published.

**Comment by netapp-pcarriga** [comment]
HI @Xinwei-Wang. The updated release notes for NetApp HCI 1.10, 1.9, 1.9P1, and 1.8P1 are now published. Thanks!
