### ISSUE TITLE
Resolved and known issues by compute firmmware bundle

### ISSUE THREAD

**Issue by hayatokurahashi** [NetAppDocs/hci#304]
Page: [Compute Firmware Bundle 2.174.0 Release Notes](https://docs.netapp.com/us-en/hci/docs/rn_compute_firmware_2.174.0.html)
It's really hard to know what actual issues were fixed in this release. BOL doesn't show "Fixed in version" for bugs in https://mysupport.netapp.com/site/bugs-online/product/HCI . Could you please consider improve this ?
![Screenshot 2023-04-19 at 10 43 26](https://user-images.githubusercontent.com/53966621/232944959-df500087-3717-43f9-8848-9617fcdaf817.png)

**Comment by netapp-pcarriga** [comment]
Hi @hayatokurahashi, thanks for your feedback. We'll look into implementing your suggestion.

**Comment by netapp-yvonneo** [comment]
@hayatokurahashi thanks for your feedback. This issue is with the SolidFire programming team for review. If you have any further questions, you can add them to this issue.
