### ISSUE TITLE
Request to update document to include Compute Firmware Bundle 2.174 

### ISSUE THREAD

**Issue by AlvinCrz** [NetAppDocs/hci#305]
Page: [Compute nodes](https://docs.netapp.com/us-en/hci/docs/fw_compute_nodes.html)

Can we request to update this document to include Compute Firmware Bundle 2.174 since its release in public already?

https://docs.netapp.com/us-en/hci/docs/fw_compute_nodes.html#component-firmware-managed-by-a-compute-firmware-bundle

**Comment by netapp-yvonneo** [comment]
@AlvinCrz thanks for your feedback. The updated doc will be published later today. I'll update here when it's available. Thanks

**Comment by netapp-yvonneo** [comment]
@AlvinCrz  details for Compute Firmware Bundle 2.174.0 have been updated here: https://docs.netapp.com/us-en/hci/docs/fw_compute_nodes.html

Closing this issue. Thanks
