### ISSUE TITLE
Compute nodes don't have storage drives to remove.

### ISSUE THREAD

**Issue by gmontjoel** [NetAppDocs/hci#311]
### Page URL

https://docs.netapp.com/us-en/hci/docs/task_hci_h610ch615crepl.html

### Page title

Replace H610C and H615C nodes

### Summary

The clause, "you should remove the drives from the cluster before you remove the failed node." is not applicable to compute nodes, since they only have a boot drive and no storage drives.  

The clause, "you should migrate the virtual machines (VMs) hosted on the node to an available host, before you remove the failed node." would be more appropriate. However, that information has already been stated, just a few lines above.

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @gmontjoel - thank you for bringing this to our attention. I'll investigate and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
Hi @gmontjoel - we've updated the documentation to remove . Thanks again for your feedback.
