### ISSUE TITLE
Feedback from a field engineer after replacing a H610C node

### ISSUE THREAD

**Issue by JamieLove-Net2** [NetAppDocs/hci#316]
### Page URL

https://docs.netapp.com/us-en/hci/docs/task_hci_hwmainoverview.html

### Page title

H-series hardware maintenance overview

### Summary

The documentation is outdated/not clear, points of confusion and issues with the documentation listed below:

1.	The listed instructions on adding the compute node to the cluster stop with HCI version 1.7 there are no instructions listed for 1.9.
2.	Before the link to replacing the HCI node never worked, but upon review it is working now. Mentioning to provide personal experiences with the documentation.
3.	The documentation also does not provide clear instructions on performing RTFI and the following steps regarding the installation of ESXi on the node. There are also no clear instructions on accessing NDE forcing the need to manually create and modify the boot.epo file on the node so that it will auto boot into ESXi.
4.	There are no steps listed for the manual process of performing the manual creation and modification of boot.epo file. I do know these steps are only to be performed by NetApp support, but the process should at least be mentioned in the event of needing to perform the manual procedure and knowing what help to request when calling into NGS.
5.	On the note of installing ESXi it mentions installing a specific version of ESXi which is an old version of the software and should be updated to reflect needing to install the version the customer is currently running on their installation.

Based on my experience with replacing HCI nodes and having to perform the manual configuration of the node due to confusion regarding NDE as to what it is and how to access it. 

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, thanks for highlighting these issues. We'll review your feedback and update the documentation accordingly.

**Comment by netapp-pcarriga** [comment]
HI @JamieLove-Net2, to help us to respond to your feedback, could you provide more information on your first point:
_The listed instructions on adding the compute node to the cluster stop with HCI version 1.7 there are no instructions listed for 1.9._
The latest document version is NetApp HCI 1.10, and the only reference to version when installing a compute node is to 'NetApp HCI Bootstrap OS version 1.6 or later'.
Thank you!

**Comment by netapp-pcarriga** [comment]
Hi @JamieLove-Net2, we've made the following updates in the documentation. Added a note to the Knowledge Base article [How to install ESXi on NetApp HCI compute node manually](https://kb.netapp.com/Legacy/NetApp_HCI/OS/How_to_install_ESXi_on_NetApp_HCI_compute_node_manually) if it's not possible to proceed with using NDE for ESXi installation and clearly called out that the ESXi versions are included as examples only.
Please let me know here in the comments sections if you have questions or further suggestions.
Thanks again for helping us improve the customer documentation.
