### ISSUE TITLE
[formatting] Missing bullet

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#36]
It looks like NetApp Fabric Orchestrator should be bulleted:

* NetApp Fabric Orchestrator 

Page: [Types of cloud services on NetApp HCI](https://docs.netapp.com/us-en/hci/docs/concept_types_cloudservices.html)

**Comment by amgrissino** [comment]
Hi, Sean, FO is not a service like CV and NKS. FO is the UI that you use to create and manage CV. So it is not bulleted. If there's something that's not clear still, let me know.
