### ISSUE TITLE
Add additional note on Service Cluster

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#37]
"Service clusters are for internal NKS use and are not available for running your applications. Service clusters are not listed in the NKS UI." - it may be obvious to some, but maybe a warning sign/note should be added to ensure users do not directly manipulate any component of service cluster (meaning VMs, networks, and so on, because it would likely disconnect them from NKS cloud service(s)).

Page: [Cluster types in cloud services on NetApp HCI](https://docs.netapp.com/us-en/hci/docs/concept_cluster_types.html)

**Comment by amgrissino** [comment]
Added another sentence not modify or delete them. Thanks, Sean. Republishing soon.
