### ISSUE TITLE
Document licensing units

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#38]
For NKS on HCI, https://cloud.netapp.com/kubernetes-service gives "per node" pricing.
On the same page, there's a "per worker" pricing for NKS (PAYGO in public cloud).

If that page doesn't become more elaborate, then maybe this page below should explain what a "node" is and few other things (such as, do NKS-on-HCI node licenses limit the size or only number of nodes).

Page: [Licensing requirements](https://docs.netapp.com/us-en/hci/docs/concept_licensing.html)

**Comment by amgrissino** [comment]
Sean, thanks for comment. Will ask HCI PM about this.

**Comment by amgrissino** [comment]
Sent question to PM and cc'd you, Sean.

**Comment by amgrissino** [comment]
Sean, licensing page is updated based on email conversations in which you were a part. Closing this. Thank you, as always!
