### ISSUE TITLE
K8s vs. NKS terminology

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#41]
Page [Kubernetes pods, volumes, and projects](https://docs.netapp.com/us-en/hci/docs/concept_kubernetes_pods_volumes_projects.html) introduces K8s terminology, but page https://docs.netapp.com/us-en/hci/docs/task_nks_creating_projects.html talks in NKS terms.

This could be improved in various ways but my personal preference would be to use the first link to explain both K8s and NKS terminology and (if possible) how one relates to another, so that readers of the second link that comes later have something to refer to.

It would be good if we had another page with an explanation of workflows because even if the concepts were to be explained, it would still be helpful to have a page on how these NKS concepts and constructs are supposed to be used (maybe for the new preview (v2) version)

**Comment by amgrissino** [comment]
Sean, emailed you for clarification.

**Comment by amgrissino** [comment]
Sean, sent some suggestions of updated terminology in email. Will supplement what we have already.

**Comment by amgrissino** [comment]
Sean, updated the terminology page. Closing this. If you see other improvements that could help, don't hesitate to reach out again. Thanks, Sean, as always!
