### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by phoebegoh** [NetAppDocs/hci#42]
Page: [Deploying cloud services on NetApp HCI overview](https://docs.netapp.com/us-en/hci/docs/task_deploying_overview.html)

https://docs.netapp.com/us-en/hci/docs/task_dfo_creating_cloud_volumes/ goes to a 404

**Comment by amgrissino** [comment]
Got it. Will fix now. Thx, Phoebe!

**Comment by amgrissino** [comment]
Fixed and closing.
