### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by wook1000** [NetAppDocs/hci#51]
Page: [Managing Kubernetes clusters on NetApp HCI overview](https://docs.netapp.com/us-en/hci/docs/task_nks_overview.html)

This link is broken: **Create a project within a workspace** in the NetApp Kubernetes Service. 
https://docs.netapp.com/us-en/hci/docs/task_nks_creating_projects.html

**Comment by amgrissino** [comment]
Thanks, wook1000. This has been fixed. Thanks for the catch! Please reload the page. Let me know if you still see an issue.
