### ISSUE TITLE
Dead link on 'Enabling cloud services' page

### ISSUE THREAD

**Issue by hulquest** [NetAppDocs/hci#62]
Near the bottom of the page the link 'See "Managing data in NetApp Cloud Volumes"' does not resolve.
Link is currently https://docs.netapp.com/us-en/hci/docs/task_cv_managing
Should be https://docs.netapp.com/us-en/hci/docs/task_cv_managing.html

**Comment by amgrissino** [comment]
On it, Kevin. Thanks for the catch!

**Comment by amgrissino** [comment]
Fixed the link. 
Thanks, again.
