### ISSUE TITLE
must have atleast 16 IP's

### ISSUE THREAD

**Issue by hciux** [NetAppDocs/hci#65]
Page: [Requirements before you begin with cloud services](https://docs.netapp.com/us-en/hci/docs/reference_requirements_beforeyoubegin.html)

must have atleast 16 IP's

**Comment by amgrissino** [comment]
Thank you, hciux! Still inquiring with team.

**Comment by hciux** [comment]
That was just the test!  You can ignore it.

Erika
________________________________

**Comment by amgrissino** [comment]
OK. closing this, hciux.
