### ISSUE TITLE
Add link to browseable edition

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#69]
In repo desc a link to https://docs.netapp.com/us-en/hci/docs/ would be helpful so that visitors who access the GH repo know where to go for a more readable version

**Comment by amgrissino** [comment]
Thanks, @scaleoutsean. Will add link to NetApp HCI Doc Center in the repo desc.

**Comment by amgrissino** [comment]
Added link you cited to the repo description. Done.
