### ISSUE TITLE
Fix step numbering (step 8 is step 1)

### ISSUE THREAD

**Issue by netapp-dbagwell** [NetAppDocs/hci#80]
Page: [Collect NetApp HCI logs](https://docs.netapp.com/us-en/hci/docs/task_hcc_collectlogs.html)

**Comment by amgrissino** [comment]
Thank you, dBagwell, for the catch. We'll fix the numbering. If you see anything else, please send them to us.

**Comment by amgrissino** [comment]
Fixed numbering. Closing the issue.
