### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by rossthomsonbsp** [NetAppDocs/hci#81]
Page: [Upgrade a management node](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_management_node.html)

On the 11.3 or later management node, run the redeploy-mnode script to retain previous management services configuration settings:

  | The script retains previous management services configuration, including configuration from the Active IQ collector service, controllers (vCenters), or proxy, depending on your settings.
-- | --

sudo /sf/packages/mnode/redeploy-mnode -mu <mnode user>

Do you run the script or not if you upgrade from 11.3 or later. Instructions are unclear.

**Comment by netapp-dbagwell** [comment]
Hi @rossthomsonbsp. Yes, you need to run the redeploy script (step 8) if you are running an upgrade from 11.3 or later after you run the iRTFI (step 7) of mNode. If there's a specific improvement we can make to the content, let us know. Thanks!

**Comment by netapp-dbagwell** [comment]
@rossthomsonbsp thanks again for your comment. If there's anything more we can do, let us know.
