### ISSUE TITLE
Unnecessary closing curvy brace in two places on one page

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#82]
```
run GET ​/health-checks​/healthCheckId} again.
```
Page: [Run Element storage health checks prior to upgrading storage](https://docs.netapp.com/us-en/hci/docs/task_hcc_upgrade_element_prechecks.html)

**Comment by amgrissino** [comment]
Thanks, @scaleoutsean. Appreciate the catch.

**Comment by scaleoutsean** [comment]
You're welcome. 

I have visited some other pages later on and it seems we use a curly brace on each side (ie a brace is missing, if we wanted to fix this in a way consistent with other content).

**Comment by amgrissino** [comment]
Hi @scaleoutsean, the topic you cited has been updated with the additional curly brace. Let us know if you see other things that require updates. Thank you, again!
