### ISSUE TITLE
Missing info for 6.7U3

### ISSUE THREAD

**Issue by scaleoutsean** [NetAppDocs/hci#90]
> The plug-in is not compatible with version 6.7 U2 of the HTML5 vSphere Web Client. It is compatible with the version 6.7 U2 vSphere Web Client for Flash. 

Compatibility info for vSphere Web Client 6.7 U3 should be mentioned as well. 

Page: [Upgrade the Element Plug-in for vCenter Server to version 4.4](https://docs.netapp.com/us-en/hci/docs/task_vcp_upgrade_plugin.html)

**Comment by netapp-dbagwell** [comment]
Hi Sean. Thanks for the feedback. 6.7 U2 is mentioned here only because it is the exception in that it is not compatible with VCP in HTML5. U3 and other versions are compatible, but we don't discuss that within the upgrade topic. [P6](https://library.netapp.com/ecm/ecm_download_file/ECMLP2866569) of the release notes has the latest compatibility matrix as does IMT.

**Comment by scaleoutsean** [comment]
Okay, then we can close this issue, although I've noticed I often get this question because users get the impression that the docs aren't up to date (that is. 6.7U2 FLEX isn't supported, and the info for later releases was not added). Perhaps a note that latest compatibility info for Element Plug-in for vSphere Web client can be found in its release notes would be useful, but I don't mind if it's not added to that page.

**Comment by netapp-dbagwell** [comment]
Hi Sean. We don't want users to get the impression that the info is out of date. Let me know what I can do to correct that. I confirmed this morning that 6.7U2 Flex is supported (as we state in release notes) and that 6.7U2 HTML5 is not supported. By “compatibility info for later releases,” which doc are you referring to? I can add a rel link to the release notes if that helps.

**Comment by scaleoutsean** [comment]
I mean, let's say today I deploy and it's 6.7U1. Now I want to upgrade to vSphere to 6.7U3 and in order to ensure Element Plug-in is also compatible, I visit this page to check how to upgrade it. If I went to read its release notes, I'd see 6.7U3 is supported, so the info is out there, but reading this page I may get the impression that 6.7U3 is not supported.

> By “compatibility info for later releases,” which doc are you referring to? 

I refer to https://docs.netapp.com/us-en/hci/docs/task_vcp_upgrade_plugin.html where 6.7U3 is not mentioned. When I read it, I thought it hasn't been updated (or that it perhaps does not support 6.7U3).

It says "It is compatible with the version 6.7 U2 vSphere Web Client for Flash. The plug-in has not yet been tested for use with vSphere 7.0" so my first guess would be it's probably supported, but I can't tell for sure, so I am not going to upgrade VCSA. 

Since there's only one release in between 6.7U2 and 7, I'd propose one of these:

* Change the note to: "It is compatible with the version 6.7 U2 vSphere Web Client for Flash and with the version 6.7U3 (Flash and HTML5). The plug-in has not yet been tested for use with vSphere 7.0"
* Add: "Detailed information about all supported vSphere versions can be found in Release Notes for Element Plug-in for vSphere"

Of course any variant of the above would work too.

**Comment by netapp-dbagwell** [comment]
Thanks Sean. Your suggested changes have been implemented: https://docs.netapp.com/us-en/hci/docs/task_vcp_upgrade_plugin.html
