### ISSUE TITLE
Can we more effectively structure the Sales & Partner Kit info

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/hci#96]
Page: [NetApp HCI Solutions Catalog](https://docs.netapp.com/us-en/hci/solutions/index.html)

Food for thought/consideration... I find it a bit disorienting that this page talks about Sales & Partner kits when this other page - 
https://docs.netapp.com/us-en/hci-solutions/sales-partner-kits.html - also appears to cover the same information.

**Comment by amgrissino** [comment]
Appreciate your feedback and food for thought. We will look at this and get back to you. Meanwhile, please feel free to send other comments.

**Comment by amgrissino** [comment]
Thanks, @adamn-ntap. We moved the content to hci-solutions. We'll remove these older files. Thanks for catching this.

**Comment by amgrissino** [comment]
We removed older files from the folder. Will now close this issue. Waited until after a release was completed, which was recently posted. Thanks again, @adamn-ntap.
